import Foundation

/// Input mode enforced for a relay session.
public enum InputControlMode: String, Sendable, Codable, Equatable {
    /// Input is blocked and the session remains read-only.
    case readOnly

    /// Input is explicitly enabled for this session.
    case enabled
}

/// Policy that governs how controlled input is allowed for a session.
public struct InputControlPolicy: Sendable, Codable, Equatable {
    /// Default mode applied when a session is attached.
    public let defaultMode: InputControlMode

    /// Whether this account/scope is allowed to enable input.
    public let canEnableInput: Bool

    /// Whether explicit user action is required before input is accepted.
    public let requiresExplicitEnable: Bool

    /// Maximum UTF-8 byte size accepted for a single input send operation.
    public let maxPayloadBytes: Int

    /// Creates a policy for controlled input behavior.
    /// - Parameters:
    ///   - defaultMode: Mode applied on initial attach. Defaults to read-only.
    ///   - canEnableInput: Whether input enablement is allowed at all.
    ///   - requiresExplicitEnable: Whether user confirmation is required first.
    ///   - maxPayloadBytes: Maximum UTF-8 payload size for one send request.
    public init(
        defaultMode: InputControlMode = .readOnly,
        canEnableInput: Bool,
        requiresExplicitEnable: Bool = true,
        maxPayloadBytes: Int = 4096
    ) {
        self.defaultMode = defaultMode
        self.canEnableInput = canEnableInput
        self.requiresExplicitEnable = requiresExplicitEnable
        // Keep payload limits valid even if upstream config sends zero/negative values.
        self.maxPayloadBytes = max(1, maxPayloadBytes)
    }

    /// Returns whether input can be sent under the current mode.
    /// - Parameter currentMode: Active mode for the session.
    public func canSendInput(currentMode: InputControlMode) -> Bool {
        guard canEnableInput else {
            return false
        }

        return currentMode == .enabled
    }
}

/// Actor identity written to audit events.
public struct InputAuditActor: Sendable, Codable, Equatable {
    /// Stable actor identifier (device/user/service id).
    public let actorID: String

    /// Human-readable actor label used in UI and logs.
    public let displayName: String

    /// Creates an audit actor descriptor.
    /// - Parameters:
    ///   - actorID: Stable actor identifier.
    ///   - displayName: Human-readable label.
    public init(actorID: String, displayName: String) {
        self.actorID = actorID
        self.displayName = displayName
    }
}

/// Operation type captured in controlled-input audits.
public enum InputAuditAction: String, Sendable, Codable, Equatable {
    /// Input mode was switched from read-only to enabled.
    case enableInput

    /// Input mode was switched from enabled to read-only.
    case disableInput

    /// Input payload was sent to the relay session.
    case sendInput
}

/// Immutable audit record for input control events.
public struct InputAuditRecord: Sendable, Codable, Equatable, Identifiable {
    /// Stable event identifier for dedupe and tracing.
    public let id: String

    /// Session identifier this event belongs to.
    public let sessionID: String

    /// Action that produced this audit event.
    public let action: InputAuditAction

    /// Actor that initiated the event.
    public let actor: InputAuditActor

    /// UTC event timestamp.
    public let occurredAt: Date

    /// Optional operator or system rationale for the event.
    public let reason: String?

    /// Creates an audit record.
    /// - Parameters:
    ///   - id: Stable event identifier.
    ///   - sessionID: Session identifier.
    ///   - action: Audit action.
    ///   - actor: Initiating actor identity.
    ///   - occurredAt: UTC timestamp.
    ///   - reason: Optional rationale.
    public init(
        id: String,
        sessionID: String,
        action: InputAuditAction,
        actor: InputAuditActor,
        occurredAt: Date,
        reason: String?
    ) {
        self.id = id
        self.sessionID = sessionID
        self.action = action
        self.actor = actor
        self.occurredAt = occurredAt
        self.reason = reason
    }
}

/// Current controlled-input state for a relay session.
public struct InputControlState: Sendable, Codable, Equatable {
    /// Session identifier for this state snapshot.
    public let sessionID: String

    /// Active input control mode.
    public let mode: InputControlMode

    /// Whether global gateway safety policy currently blocks input.
    public let globalInputDisabled: Bool

    /// When this state was last changed in UTC.
    public let updatedAt: Date

    /// Audit record generated by the state transition.
    public let auditRecord: InputAuditRecord

    /// Creates an input control state snapshot.
    /// - Parameters:
    ///   - sessionID: Session identifier.
    ///   - mode: Active mode.
    ///   - globalInputDisabled: Global kill-switch state.
    ///   - updatedAt: UTC last update timestamp.
    ///   - auditRecord: Transition audit record.
    public init(
        sessionID: String,
        mode: InputControlMode,
        globalInputDisabled: Bool = false,
        updatedAt: Date,
        auditRecord: InputAuditRecord
    ) {
        self.sessionID = sessionID
        self.mode = mode
        self.globalInputDisabled = globalInputDisabled
        self.updatedAt = updatedAt
        self.auditRecord = auditRecord
    }
}

/// Request payload used to enable controlled input for a session.
public struct EnableInputRequest: Sendable, Codable, Equatable {
    /// Session that should move to enabled input mode.
    public let sessionID: String

    /// Actor performing the mode change.
    public let actor: InputAuditActor

    /// Optional rationale provided during the enable action.
    public let reason: String?

    /// Creates an enable-input request.
    /// - Parameters:
    ///   - sessionID: Session identifier.
    ///   - actor: Initiating actor.
    ///   - reason: Optional rationale.
    public init(sessionID: String, actor: InputAuditActor, reason: String?) {
        self.sessionID = sessionID
        self.actor = actor
        self.reason = reason
    }
}

/// Request payload used to disable controlled input for a session.
public struct DisableInputRequest: Sendable, Codable, Equatable {
    /// Session that should return to read-only mode.
    public let sessionID: String

    /// Actor performing the mode change.
    public let actor: InputAuditActor

    /// Optional rationale provided during the disable action.
    public let reason: String?

    /// Creates a disable-input request.
    /// - Parameters:
    ///   - sessionID: Session identifier.
    ///   - actor: Initiating actor.
    ///   - reason: Optional rationale.
    public init(sessionID: String, actor: InputAuditActor, reason: String?) {
        self.sessionID = sessionID
        self.actor = actor
        self.reason = reason
    }
}

/// Input payload accepted by the relay for a controlled send operation.
public struct SessionInputPayload: Sendable, Codable, Equatable {
    /// Raw UTF-8 terminal text to send.
    public let text: String

    /// Creates a session input payload.
    /// - Parameter text: UTF-8 terminal text.
    public init(text: String) {
        self.text = text
    }

    /// UTF-8 encoded payload byte count.
    public var utf8ByteCount: Int {
        text.lengthOfBytes(using: .utf8)
    }
}

/// Request payload used to send controlled input to a relay session.
public struct SendInputRequest: Sendable, Codable, Equatable {
    /// Session receiving the input payload.
    public let sessionID: String

    /// Actor issuing the send operation.
    public let actor: InputAuditActor

    /// Raw text payload to deliver.
    public let payload: SessionInputPayload

    /// Creates a send-input request.
    /// - Parameters:
    ///   - sessionID: Session identifier.
    ///   - actor: Initiating actor.
    ///   - payload: Text payload.
    public init(sessionID: String, actor: InputAuditActor, payload: SessionInputPayload) {
        self.sessionID = sessionID
        self.actor = actor
        self.payload = payload
    }
}

/// Controlled input operations for iOS M2 session domain flows.
public protocol ControlledInputServicing: Sendable {
    /// Enables input for a session and returns the updated mode snapshot.
    /// - Parameter request: Enable-input payload.
    func enableInput(request: EnableInputRequest) async throws -> InputControlState

    /// Disables input for a session and returns the updated mode snapshot.
    /// - Parameter request: Disable-input payload.
    func disableInput(request: DisableInputRequest) async throws -> InputControlState

    /// Sends user input and returns the resulting audit record.
    /// - Parameter request: Send-input payload.
    func sendInput(request: SendInputRequest) async throws -> InputAuditRecord
}
